apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      name: grafana
      labels:
        app: grafana
    spec:
      tolerations:
        - key: "name-mb"
          #operator: "Exists"
          value: "monitoring"
          effect: "NoSchedule"
      imagePullSecrets:
        - name: regcreds
      containers:
      - name: grafana
        image: swr.af-south-1.myhuaweicloud.com/motobill-prod/grafana:latest
        ports:
        - name: grafana
          containerPort: 3000
        resources:
          limits:
            memory: 400M
            cpu: 200m
          requests: 
            memory: 400M
            cpu: 200m
        volumeMounts:
          - mountPath: /var/lib/grafana
            name: grafana-storage
          - mountPath: /etc/grafana/provisioning/datasources
            name: grafana-datasources
            readOnly: false
      volumes:
        - name: grafana-storage
          persistentVolumeClaim: 
            claimName: grafana-pvc
        - name: grafana-datasources
          configMap:
              defaultMode: 420
              name: grafana-datasources


